# encoding: utf-8
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'compendium-api', git: 'https://github.com/mlintern/compendium-api'
gem 'nretnil-fake-data', git: 'https://github.com/mlintern/nretnil-fake-data'
gem 'nretnil-password', git: 'https://github.com/mlintern/nretnil-password'
gem 'sinatra'
gem 'sinatra-contrib'
